source ~/.aliases

eval "$(/opt/homebrew/bin/brew shellenv)"

# For stuff that you don't want commited
if [ -f ~/.zprofile.local ]; then
  source ~/.zprofile.local
fi

# For stuff that you don't want commited
if [ -f ~/.zsh/extra ]; then
  source ~/.zsh/extra
fi
