
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ZSH_DISABLE_COMPFIX=true

ZSH_THEME="intheloop"

source $ZSH/oh-my-zsh.sh

export DOTFILES="$HOME/.dotfiles"

# Source local zshrc if exists
test -f ~/.zshrc.local && source ~/.zshrc.local
