
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES="$HOME/.dotfiles"

source $ZSH/oh-my-zsh.sh

# Source local zshrc if exists
test -f ~/.zshrc.local && source ~/.zshrc.local